### ISSUE TITLE
Remove Unwanted Pop-up

### ISSUE THREAD

**Issue by uzaxirr** [integrateme-co/frontend#2]
This needs To be removed

![Screenshot from 2021-11-01 08-39-56](https://user-images.githubusercontent.com/72073401/139616594-f9717c8e-a7f1-4191-bf1d-8b80461f2cbc.png)

**Comment by sayamsamal** [comment]
Fixed with commit d3bf7920e418a48caa60071f8e8f0043fb530750

**Comment by sayamsamal** [comment]
Fixed with commit d3bf7920e418a48caa60071f8e8f0043fb530750
